name: myBinder-environment

dependencies:
  - python>=3.6
  - biopython=1.72
  - numpy=1.15.4
  - nose
  - requests=2.19.1
  - matplotlib=3.0.2
  - ipywidgets=7.4.2
  - seaborn=0.8.1
  - pandas=0.23.4
  - pyspark=2.4.0
  - py4j=0.10.7
  - pyarrow=0.11.1
  - python-dateutil
  - sympy=1.1.1
  - xlrd=1.1.0
  - pip:
      - py3Dmol==0.8.0
      - mmtf-python==1.1.2
      - git+https://github.com/sbl-sdsc/mmtf-pyspark.git#egg=mmtf-pyspark[complete]
