name: mmtf-pyspark 

dependencies:
  - python>=3.6
  - openjdk==8.0.152
  - pyspark==2.3.2
  - biopython==1.72
  - numpy==1.15.4
  - ipywidgets==7.4.2
  - mmtf-python==1.1.2
  - requests==2.20.0
  - matplotlib==2.2.3
  - seaborn==0.8.1
  - sympy==1.1.1
  - scipy==1.1.0
  - scikit-learn==0.20.0
  - pandas==0.23.4
  - pyarrow==0.11.1
  - py4j==0.10.7
  - xlrd==1.1.0
  - pip
  - pip:
      - py3Dmol==0.8.0
      - msgpack==0.5.6
      - git+https://github.com/pwrose/mmtf-pyspark.git 
